// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pzJx5O0bblQcuVj8DRL2TQKx8LaoELE',
    appId: '1:373407548044:android:06d243374482eeb65df1a9',
    messagingSenderId: '373407548044',
    projectId: 'flatch-e772e',
    storageBucket: 'flatch-e772e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJR4m9AncWrKQb9aITbXQearl-OPrljp0',
    appId: '1:373407548044:ios:df9896cf7aabf5ae5df1a9',
    messagingSenderId: '373407548044',
    projectId: 'flatch-e772e',
    storageBucket: 'flatch-e772e.firebasestorage.app',
    androidClientId: '373407548044-n8te0q0aco0c2becpm1hcj994lqa1k64.apps.googleusercontent.com',
    iosClientId: '373407548044-5eqls5qaqjsmibt6hmas97sigchc2ab3.apps.googleusercontent.com',
    iosBundleId: 'com.flatch.flickedflatch',
  );

}